###

GET {{host}}/buckets
Content-Type: application/json

###

POST {{host}}/list-objects
Content-Type: application/json

{
  "bucket": "any_bucket",
  "maxKeys": 1
}

###

PUT {{host}}/put-object
Content-Type: application/json

{
  "bucket": "any_bucket",
  "path": "file/test.png"
}

###